# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: PR Test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  IS_GITHUB_RUNNER: true

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup MicroMamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: false
      - name: MicroMamba info
        shell: bash -el {0}
        run: micromamba info
      - name: Install conda environment
        shell: bash -el {0}
        run: pushd canvas && micromamba create -f environment.yml -p ./venv && popd
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
        with:
          arguments: clean test --info
